spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
server:
  port: 8001
#配置Mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名自动映射
  global-config: #逻辑删除功能
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

shortlink:
  api:
    amap-key: c1ce6eed90ea948651c4ad0ae6793cdc
logging:
    level:
        org.springframework.ai: debug
        com.llj.ai: debug